#!/usr/bin/env bash
set -euo pipefail

echo ""
echo "=============================================================="
echo " Dynatrace AI Observability Workshop"
echo " Setting up your Codespace"
echo "=============================================================="
echo ""

REPO_DIR="$(git rev-parse --show-toplevel)"
ENV_FILE="$REPO_DIR/.env"

echo "Repository: $REPO_DIR"
echo ""
echo "Installing Python dependencies..."
python -m pip install --upgrade pip
python -m pip install -r "$REPO_DIR/app/requirements.txt"
echo "Python dependencies installed."

if [ ! -f "$ENV_FILE" ]; then
  echo ""
  echo "Creating the guided .env configuration file..."

  cat > "$ENV_FILE" <<'ENVEOF'
# =====================================================================
# DYNATRACE AI + MCP WORKSHOP CONFIGURATION
# =====================================================================
#
# STEP 1
# In the workshop guide sidebar, choose a short Workshop ID that you
# will recognise in Dynatrace, for example:
#
#   marc-mas
#   acme-alex
#   partner07
#
# Do not use an email address. ATTENDEE_ID is filled automatically when
# you run the personalised configure.sh command shown in the guide.
#
# STEP 2
# Replace every PASTE_HERE value below with the shared values supplied
# by the instructor.
#
# STEP 3
# Save this file, return to the guide and copy the personalised command:
#
#   bash .devcontainer/configure.sh --attendee-id=YOUR_WORKSHOP_ID
#
# Rules:
# - Do not add quotation marks.
# - Do not add spaces before or after the equals sign.
# - Do not commit this file. It contains workshop credentials.
# =====================================================================


# ---------------------------------------------------------------------
# 1. WORKSHOP ID
# ---------------------------------------------------------------------
#
# Leave this empty. configure.sh fills it from the personalised command
# generated by the workshop guide.

ATTENDEE_ID=


# ---------------------------------------------------------------------
# 2. AI GATEWAY
# ---------------------------------------------------------------------
#
# LLM_BASE_URL must end with /v1
# LLM_API_KEY normally starts with sk-workshop-
# LLM_CHAT_MODEL must remain workshop-chat

LLM_BASE_URL=http://INSTRUCTOR_GATEWAY:4000/v1
LLM_API_KEY=PASTE_HERE
LLM_CHAT_MODEL=workshop-chat


# ---------------------------------------------------------------------
# 3. DYNATRACE TELEMETRY INGESTION
# ---------------------------------------------------------------------
#
# DT_ENDPOINT must end with /api/v2/otlp
# DT_API_TOKEN normally starts with dt0c01.

DT_ENDPOINT=PASTE_HERE
DT_API_TOKEN=PASTE_HERE


# ---------------------------------------------------------------------
# 4. DYNATRACE MCP
# ---------------------------------------------------------------------
#
# DT_MCP_BEARER_TOKEN normally starts with dt0s16.

DT_MCP_BEARER_TOKEN=PASTE_HERE


# =====================================================================
# COMPLETED FILE EXAMPLE
# =====================================================================
#
# ATTENDEE_ID=acme-alex
# LLM_BASE_URL=http://INSTRUCTOR_GATEWAY:4000/v1
# LLM_API_KEY=sk-workshop-INSTRUCTOR_PROVIDED
# LLM_CHAT_MODEL=workshop-chat
# DT_ENDPOINT=https://INSTRUCTOR_ENV.live.dynatrace.com/api/v2/otlp
# DT_API_TOKEN=dt0c01.INSTRUCTOR_PROVIDED
# DT_MCP_BEARER_TOKEN=dt0s16.INSTRUCTOR_PROVIDED
#
# The values above are examples only. Use the instructor credential card.
# =====================================================================
ENVEOF

  echo "Created: $ENV_FILE"
else
  echo ""
  echo ".env already exists. Existing values were preserved."
fi

echo ""
echo "=============================================================="
echo " ACTION REQUIRED"
echo "=============================================================="
echo ""
echo "1. In the guide sidebar, set your recognisable Workshop ID."
echo ""
echo "2. Open .env in the VS Code Explorer."
echo ""
echo "3. Replace every PASTE_HERE value with the instructor values."
echo ""
echo "4. Save .env."
echo ""
echo "5. Return to Lab 0 and copy its personalised configure command."
echo "   It will look like:"
echo ""
echo "   bash .devcontainer/configure.sh --attendee-id=acme-alex"
echo ""
echo "6. Run that command in this terminal."
echo ""
echo "Do not run the application until configure.sh succeeds."
echo "=============================================================="
echo ""
